##. . . . . . . . . . . . . . . . . . . . . . . . . . . . .
## Phase 5 Configuration
##. . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# These are the settings for configuration of phase5, where 
# final observables (yields, widths) are calculated after flow
# subtraction is done in the final step

##. . . . . . . . . . . . . . . . . . . . . . . . . . . . .
## Path to the directory where the Intermediate Projection files are stored
file_path: "~/cern/gammaHadron/wrk/phase4/output/" 
##. . . . . . . . . . . . . . . . . . . . . . . . . . . . .
## Names of the Intermediate root files with projected histograms

# The central file
file_name_central: "Corr4MB/RPF_Pi0_Corr4MB_PtBin$PTBIN_SBSel$BKGSEL_Cent$CENTBIN_PurChoice$PURITYCHOICE.root"
#file_name_central: "RPFSub_Pi0_Corr4MB_PtBin1_Cent1_PurChoice1.root"

##. . . . . . . . . . . . . . . . . . . . . . . . . . . . .
## Path to directory where output files and plots should be stored
#output_dir: "/home/alidock/cern/gammaHadron/wrk/phase3/output/FullProcess/Pi0_t23_t24_PtBin2_Cent1"
output_dir: "output/Corr4MB/PtBin$PTBIN_Cent$CENTBIN/PurChoice$PURITYCHOICE_SBSel$BKGSEL"

##. . . . . . . . . . . . . . . . . . . . . . . . . . . . .
## Label for projection root files, if created
label: "Pi0_Corr4MB_PtBin$PTBIN_Cent$CENTBIN_PurChoice$PURITYCHOICE_SBSel$BKGSEL"
##. . . . . . . . . . . . . . . . . . . . . . . . . . . . .

# RPF method to use (0 -> C++,1 -> Python)
rpf_method: 1



